# -*- coding: utf-8 -*-
#!/usr/bin/env python

import tornado.web
import tornado.gen
from mod.auth.Base_Handler import BaseHandler

#/discover/discover_page
class DiscoverPageHandler(BaseHandler):
	def get(self):#发现主页面
		content=[
					{'square':'',
					'state_img':'1',
			       'id':'1',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'',
					'state_img':'2',
			       'id':'2',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'',
					'state_img':'3',
			       'id':'3',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'',
					'state_img':'4',
			       'id':'4',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'uc-container_square',
					'state_img':'5',
			       'id':'5',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'uc-container_square',
					'state_img':'6',
			       'id':'6',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'uc-container_square',
					'state_img':'7',
			       'id':'7',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'uc-container_square',
					'state_img':'8',
			       'id':'8',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'',
					'state_img':'9',
			       'id':'9',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			
        			{'square':'',
					'state_img':'10',
			       'id':'10',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'',
					'state_img':'11',
			       'id':'11',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'},
        			{'square':'',
					'state_img':'12',
			       'id':'12',
                   'state_title':'lala',
        			'state_writer_link':'/plans',
        			'state_writer':'Andrew'}
        ]
		self.render('discoverpage.html',user=self.current_user,content=content)